const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get(k,d=[]){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
function uid(){return Math.random().toString(36).slice(2,9)}
function money(n){return new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(Number(n||0))}
function nav(){return `<nav class="nav"><a class="brand" href="index.html"><span class="orb"></span><span>Green Dial</span></a><div class="links"><a href="buy.html">Buy Nearby</a><a href="sell.html">Sell</a><a href="add-watch.html">Add Watch</a><a href="messages.html">Messages</a><a href="profile.html">Profile</a></div><a class="btn" href="buy.html">Browse Watches</a></nav>`}
function footer(){return `<footer class="footer"><div class="container"><b>Green Dial</b><span>Local luxury watch marketplace. Built for real collectors, real listings, real conversations.</span></div></footer>`}
function boot(){const n=$('#nav'); if(n)n.innerHTML=nav(); const f=$('#footer'); if(f)f.innerHTML=footer(); renderListings(); renderProfile();}
function saveWatch(e){e.preventDefault(); const fd=new FormData(e.target); const w=Object.fromEntries(fd.entries()); w.id=uid(); w.createdAt=new Date().toISOString(); w.photo=''; const file=fd.get('photo'); const done=()=>{const list=store.get('watches'); list.unshift(w); store.set('watches',list); location.href='my-listings.html'}; if(file&&file.size){const reader=new FileReader(); reader.onload=()=>{w.photo=reader.result; done()}; reader.readAsDataURL(file)} else done();}
function saveProfile(e){e.preventDefault(); const data=Object.fromEntries(new FormData(e.target).entries()); store.set('profile',data); alert('Profile saved on this browser. When backend is added, this will become a real account.'); renderProfile();}
function renderListings(){const mount=$('#listings'); if(!mount)return; const watches=store.get('watches'); if(!watches.length){mount.innerHTML=`<div class="card empty"><h3>No watches listed yet</h3><p class="muted">This is ready for real users. Once someone adds a watch, it will appear here.</p><a class="btn green" href="add-watch.html">Add the first watch</a></div>`; return} mount.innerHTML=watches.map(w=>`<article class="card listing"><div class="photo" ${w.photo?`style="background-image:url('${w.photo}');background-size:cover;background-position:center"`:''}>${w.photo?'':''}</div><div class="body"><span class="badge">${w.city||'Location added'}</span><h3>${w.brand||'Watch'} ${w.model||''}</h3><p class="muted">${w.condition||'Condition'} · ${w.year||'Year'} · ${w.box||'Box/Papers'}</p><div class="price">${money(w.price)}</div><p>${w.description||''}</p><a class="btn light" href="watch-detail.html?id=${w.id}">View listing</a></div></article>`).join('')}
function renderDetail(){const id=new URLSearchParams(location.search).get('id'); const w=store.get('watches').find(x=>x.id===id); const mount=$('#detail'); if(!mount)return; if(!w){mount.innerHTML=`<div class="card empty"><h3>No listing selected</h3><p class="muted">Open a watch from the Buy Nearby page or add your own real listing.</p><a class="btn green" href="buy.html">Browse Watches</a></div>`;return} mount.innerHTML=`<div class="grid grid2"><div class="card"><div class="photo" style="height:520px;${w.photo?`background-image:url('${w.photo}');background-size:cover;background-position:center`:''}">${w.photo?'':''}</div></div><div class="card"><span class="badge">${w.city}</span><h1 class="title" style="font-size:60px">${w.brand} ${w.model}</h1><p class="price">${money(w.price)}</p><p class="muted">${w.condition} · ${w.year} · ${w.box}</p><p>${w.description||'Seller has not added extra notes yet.'}</p><div class="tabs"><a class="btn green" href="messages.html">Message Seller</a><button class="btn light">Make Offer</button><button class="btn light" onclick="saveListing('${w.id}')">Save</button></div></div></div>`}
function saveListing(id){const s=store.get('saved'); if(!s.includes(id))s.push(id); store.set('saved',s); alert('Saved.');}
function renderProfile(){const p=store.get('profile',null); const mounts=$$('.profile-area'); if(!mounts.length)return; mounts.forEach(m=>{m.innerHTML=p?`<div class="card"><h2>${p.name||'Collector'}</h2><p>${p.city||'City'} · ${p.type||'Collector'}</p><p class="muted">${p.bio||'No bio added yet.'}</p><a class="btn light" href="profile.html">Edit profile</a></div>`:`<div class="card empty"><h3>Create your real profile</h3><p class="muted">No fake users. Add your own seller/buyer profile first.</p><a class="btn green" href="profile.html">Create Profile</a></div>`})}
function clearDemo(){localStorage.removeItem('watches');localStorage.removeItem('profile');localStorage.removeItem('saved');location.reload()}
document.addEventListener('DOMContentLoaded',()=>{boot();renderDetail(); const aw=$('#watchForm'); if(aw)aw.addEventListener('submit',saveWatch); const pf=$('#profileForm'); if(pf)pf.addEventListener('submit',saveProfile);});
